# Generated by Django 5.2.5 on 2025-08-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
