# Generated by Django 5.2.9 on 2026-03-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shop_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='default_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price from master data', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Effective price after discount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
